name: "🔀  Pull Request"

on:
  pull_request_target:

concurrency:
  group: pull-request-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  infrastructure:
    name: "👷️  CI (Infrastructure)"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: "🐙️  Checkout"
        uses: actions/checkout@v4

      - name: "💽️  Setup"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: "🧪  Test"
        run: dotnet test --verbosity quiet
        working-directory: ./src/Infrastructure

  orchestrator:
    name: "👷️  CI (Orchestrator)"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: "🐙️  Checkout"
        uses: actions/checkout@v4

      - name: "💽️  Setup"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: "🧪  Test"
        run: dotnet test --verbosity quiet
        working-directory: ./src/Service.Orchestrator

      - name: "⬆️  GraphQL Schema (upload)"
        uses: ./.github/actions/schema
        with:
          working-directory: src/Service.Orchestrator/src/HttpApi

  encoder:
    name: "👷️  CI (Encoder)"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: "🐙️  Checkout"
        uses: actions/checkout@v4

      - name: "💽️  Setup"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: "🧪  Test"
        run: dotnet test --verbosity quiet
        working-directory: ./src/Service.Encoder

  app:
    name: "👷️  CI (App)"
    timeout-minutes: 20
    runs-on: ubuntu-latest
    needs: [orchestrator]
    strategy:
      fail-fast: false
    steps:
      - name: "🐙️  Checkout"
        uses: actions/checkout@v4

      - name: "💽️  Setup"
        uses: ./.github/actions/setup

      - name: "🔺️  Cache (pnpm)"
        uses: ./.github/actions/cache

      - name: "📦  Install"
        shell: bash
        working-directory: ./app
        run: |
          pnpm install --frozen-lockfile

      - name: "⬇️  GraphQL Schema (download)"
        uses: actions/download-artifact@v4
        with:
          name: schema-${{ github.run_number }}.graphql
          path: ./app

      - name: "🔺️  Cache (nextjs)"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/app/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: "🏗️  Build"
        working-directory: ./app
        shell: bash
        run: |
          pnpm run build

      # - name: "🧪  Test"
      #   working-directory: ./app
      #   shell: bash
      #   run: |
      #     pnpm run test
